<?php

namespace ContainerJkux4Jp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y0jLYATService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y0jLYAT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y0jLYAT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\GenreController::add' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\HomeController::Show' => ['privates', '.service_locator.1tPq.VI', 'get_ServiceLocator_1tPq_VIService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController::onAuthenticationSuccess' => ['privates', '.service_locator.pGsgVxs', 'get_ServiceLocator_PGsgVxsService', true],
            'App\\Controller\\ProductController::GenreAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController::createAction' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\ProductController::deleteAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController::detailsAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController::editAction' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\ProductController::listAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController::saveChanges' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\GenreController:add' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\HomeController:Show' => ['privates', '.service_locator.1tPq.VI', 'get_ServiceLocator_1tPq_VIService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\LoginController:onAuthenticationSuccess' => ['privates', '.service_locator.pGsgVxs', 'get_ServiceLocator_PGsgVxsService', true],
            'App\\Controller\\ProductController:GenreAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController:createAction' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\ProductController:deleteAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController:detailsAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController:editAction' => ['privates', '.service_locator.aUsFPsv', 'get_ServiceLocator_AUsFPsvService', true],
            'App\\Controller\\ProductController:listAction' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ProductController:saveChanges' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\GenreController::add' => '?',
            'App\\Controller\\HomeController::Show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\LoginController::onAuthenticationSuccess' => '?',
            'App\\Controller\\ProductController::GenreAction' => '?',
            'App\\Controller\\ProductController::createAction' => '?',
            'App\\Controller\\ProductController::deleteAction' => '?',
            'App\\Controller\\ProductController::detailsAction' => '?',
            'App\\Controller\\ProductController::editAction' => '?',
            'App\\Controller\\ProductController::listAction' => '?',
            'App\\Controller\\ProductController::saveChanges' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\GenreController:add' => '?',
            'App\\Controller\\HomeController:Show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\LoginController:onAuthenticationSuccess' => '?',
            'App\\Controller\\ProductController:GenreAction' => '?',
            'App\\Controller\\ProductController:createAction' => '?',
            'App\\Controller\\ProductController:deleteAction' => '?',
            'App\\Controller\\ProductController:detailsAction' => '?',
            'App\\Controller\\ProductController:editAction' => '?',
            'App\\Controller\\ProductController:listAction' => '?',
            'App\\Controller\\ProductController:saveChanges' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
