<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJkux4Jp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJkux4Jp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJkux4Jp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJkux4Jp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJkux4Jp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jkux4Jp',
    'container.build_id' => 'e9e00e7d',
    'container.build_time' => 1682007181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJkux4Jp');
