<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'app_category' => [[], ['_controller' => 'App\\Controller\\CategoryController::index'], [], [['text', '/category']], [], [], []],
    'create_category' => [[], ['_controller' => 'App\\Controller\\CategoryController::create'], [], [['text', '/category/create']], [], [], []],
    'app_contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'create_genre' => [[], ['_controller' => 'App\\Controller\\GenreController::add'], [], [['text', '/genre/create/']], [], [], []],
    'view_product' => [['id'], ['_controller' => 'App\\Controller\\HomeController::Show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product_view']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'product_list' => [[], ['_controller' => 'App\\Controller\\ProductController::listAction'], [], [['text', '/']], [], [], []],
    'product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::deleteAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], [], []],
    'product_details' => [['id'], ['_controller' => 'App\\Controller\\ProductController::detailsAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/details']], [], [], []],
    'product_create' => [[], ['_controller' => 'App\\Controller\\ProductController::createAction'], [], [['text', '/create/']], [], [], []],
    'product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::editAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit']], [], [], []],
    'productByGenre' => [['id'], ['_controller' => 'App\\Controller\\ProductController::GenreAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/productByGenre']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
];
